# Generated by Django 2.2.5 on 2019-09-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
