# Generated by Django 2.2.5 on 2019-09-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0003_album'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Record',
        ),
    ]
