# Generated by Django 2.2.5 on 2019-09-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0005_auto_20190923_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
