# Generated by Django 2.2.5 on 2019-09-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0006_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in U$S', max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
