# Generated by Django 2.2.5 on 2019-09-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0007_auto_20190923_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pasta',
        ),
    ]
