# Generated by Django 2.2.5 on 2019-09-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0008_delete_pasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
