# Generated by Django 2.2.5 on 2019-09-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0009_auto_20190923_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('tracklist', models.CharField(max_length=64)),
                ('track_time', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
