# Generated by Django 2.2.5 on 2019-09-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0010_auto_20190923_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='track_time',
        ),
        migrations.RemoveField(
            model_name='album',
            name='tracklist',
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=10)),
                ('albums', models.ManyToManyField(blank=True, related_name='song', to='band_profile.Album')),
            ],
        ),
    ]
