# Generated by Django 2.2.5 on 2019-09-23 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0011_auto_20190923_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track', to='band_profile.Song'),
        ),
    ]
