# Generated by Django 2.2.5 on 2019-09-23 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0012_auto_20190923_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track', to='band_profile.Song'),
        ),
    ]
