# Generated by Django 2.2.5 on 2019-09-25 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0014_song_tracknumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tracks',
        ),
        migrations.AddField(
            model_name='song',
            name='onAlbum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track', to='band_profile.Album'),
        ),
    ]
