# Generated by Django 2.2.5 on 2019-09-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0015_auto_20190925_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='onAlbum',
        ),
        migrations.AddField(
            model_name='song',
            name='onAlbum',
            field=models.ManyToManyField(blank=True, null=True, related_name='track', to='band_profile.Album'),
        ),
    ]
