# Generated by Django 2.2.5 on 2019-09-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0016_auto_20190925_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='onAlbum',
            field=models.ManyToManyField(blank=True, related_name='track', to='band_profile.Album'),
        ),
    ]
