# Generated by Django 2.2.5 on 2019-09-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0017_auto_20190925_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='onAlbum',
        ),
        migrations.AddField(
            model_name='album',
            name='onAlbum',
            field=models.ManyToManyField(blank=True, related_name='track', to='band_profile.Song'),
        ),
    ]
