# Generated by Django 2.2.5 on 2019-09-26 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0018_auto_20190925_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='onAlbum',
        ),
        migrations.AddField(
            model_name='song',
            name='onAlbum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track', to='band_profile.Album'),
        ),
    ]
