# Generated by Django 2.2.5 on 2019-09-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0019_auto_20190925_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
