# Generated by Django 2.2.5 on 2019-09-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band_profile', '0020_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='onAlbum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='band_profile.Album'),
        ),
    ]
